name: WordFinder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install PyMongo
      run: |
        pip install pymongo
    - name: Install Flask
      run: |
        pip install flask
    - name: Run Flask app
      run: |
        export FLASK_APP=src/app.py
        flask run --host=0.0.0.0 --port=5000
